### ISSUE TITLE
Unable to import an exported common resource - Error: must supply a Common Resource name and filepath to a json definition

### ISSUE THREAD

**Issue by gdesouter** [ghchinoy/cectl#6] opened 2018-01-25 21:10 UTC

**Comment by ghchinoy** [comment] 2018-01-26 02:16
I tried the following (v0.5.0 with extended help on error):

```
 $ cectl resources import qsc.json --profile apitester
must supply a Common Resource name and a filepath to a json definition
Import a Common Resource to the platform, given a name and a json definition of that Common Resource

Usage:
  cectl resources import <name> <filepath.json> [flags]

Flags:
  -h, --help   help for import

Global Flags:
  -c, --curl             show curl command
  -j, --json             output as json
      --profile string   profile name (default "default")
```


```
$ cectl resources import test qsc.json --profile apitester
Added common object resource: test
Field levels: organization
    PATH    |  TYPE
+-----------+--------+
  Email     | string
  FirstName | string
  Phone     | string
  LastName  | string
  OldPhone  | string

$ cectl resources list --profile apitester
       NAME      | MAPPED INSTANCES | #  |                  FIELDS
+----------------+------------------+----+------------------------------------------+
  qsc            |                0 |  5 |  [Email, FirstName, Phone, LastName,
                 |                  |    | OldPhone]
  test           |                0 |  5 |  [Email, FirstName, Phone, LastName,
                 |                  |    | OldPhone]
  common-contact |                0 | 11 |  [country, firstName, lastName, city,
                 |                  |    | phone, street, postalCode, name, id,
                 |                  |    | state, email]
```

**Comment by ghchinoy** [comment] 2018-01-27 20:25
Unable to reproduce. Closing.
Please feel free to reopen or submit if you have more information.

**Closed by ghchinoy** 2018-01-27 20:25 UTC
